simplemoc/accounts/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from simplemoc.accounts.views import register
from simplemoc.accounts.views import dashboard
from simplemoc.accounts.views import edit

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('entrar/',auth_views.LoginView.as_view(),name='login'),
    path('sair/',auth_views.LogoutView.as_view(),name='logout'),
    path('cadastre-se/', register, name='register'),
    path('editar/', edit, name='edit'),
]

simplemoc/core/urls.py
from django.urls import path
from simplemoc.core.views import home
from simplemoc.core.views import contact

urlpatterns = [
    path('', home, name='home'),
    path('contato/', contact, name='contact'),
]

simplemoc/courses/urls.py
from django.urls import path
from simplemoc.courses.views import index
from simplemoc.courses.views import details

urlpatterns = [
    path('', index, name='index'),
    #path('<int:pk>/', details, name='details'),
    path('<slug:slug>/', details, name='details'),
]

simplemoc/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#from simplemoc.courses.views import details

urlpatterns = [
    path('', include(('simplemoc.core.urls', 'core'), namespace='core')),
    path('conta/', include(('simplemoc.accounts.urls', 'accounts'), namespace='accounts')),
    path('cursos/', include(('simplemoc.courses.urls', 'courses'), namespace='courses')),
    path('admin/', admin.site.urls),
    #path('<slug:slug>/', details, name='details'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemoc/accounts/models.py
from django.db import models

# Create your models here.

simplemoc/core/models.py
from django.db import models

# Create your models here.

simplemoc/courses/models.py
import os
from django.db import models
from django.urls import reverse


# Create your models here.
class CourseManager(models.Manager):

    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) | \
            models.Q(descripton__icontains=query)
        )

class Courses(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    descripton = models.TextField('Descricao Simples, blank=True')
    about = models.TextField('Sobre o curso', blank=True)
    start_date = models.DateField('data de inicio', null=True, blank=True)
    image = models.ImageField(upload_to='couses/image', verbose_name='imagem', null=True, blank=True)

    created_at = models.DateTimeField('criado em', auto_now_add=True)

    updated_at = models.DateTimeField('atualizado em', auto_now_add=True)

    objects = CourseManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('courses:details', args=[self.slug])

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name']

simplemoc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Já Existe usuário com esse E-mail')
        return email


    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

simplemoc/courses/forms.py
from django import forms
from django.core.mail import send_mail

from django.conf import settings

from simplemoc.core.mail import send_mail_template

class ContactCourse(forms.Form):

    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(
        label='Mensagem/Dúvida', widget=forms.Textarea
    )

    def send_mail(self, course):
        subject = '[%s] Contato Curso'% course
        message = 'Nome: %(name)s;E-mail: %(email)s'
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        template_name = 'contact_email.html'
        send_mail_template(
            subject, template_name, context, [settings.CONTACT_EMAIL]
        )

simplemoc/accounts/views.py
from re import template

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm

@login_required
def dashboard(request):
    template_name = 'registration/dashboard.html'
    return render(request, template_name)

def register(request):
    template_name = 'registration/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('core:home')
    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)

@login_required
def edit(request):
    template_name = 'accounts/edit.html'
    return render(request, template_name)

# Create your views here.

simplemoc/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contato.html')

simplemoc/courses/views.py
from django.shortcuts import render, get_object_or_404
from .models import Courses
from .forms import ContactCourse

# Create your views here.

def index(request):
    courses = Courses.objects.all()
    template_name = 'courses/index.html'
    context = {
        'courses': courses
    }
    return render(request, template_name, context)
'''''
def details(request, pk):
    course = Courses.objects.get(pk=pk)
    context = {
        'course': course
    }
    template_name = 'courses/details.html'
    return render(request, template_name, context)

'''''
def details(request, slug):
    course = get_object_or_404(Courses, slug=slug)
    context = {}
    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_mail(course)
            form = ContactCourse()
    else:
        form = ContactCourse()
    context['course'] = course
    context['form'] = form
    template_name = 'courses/details.html'
    return render(request, template_name, context)

simplemoc/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple MOOC - Uma simples plataforma de ensino a distância" />
    <title>Simple MOOC</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />


    <title>Contact Form 01</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="{% static 'css/styles_dois.css' %}">
</head>

<body>

<div class="content">
    <div class="header">
        <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
            <a class="pure-menu-heading" href="">SIMPLE MOOC</a>
            <ul>
                <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
                <li><a href="{% url 'courses:index' %}">Cursos</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'accounts:dashboard' %}">Painel</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
                {% endif %}
                <li><a href="{% url 'core:contact' %}">Contato</a></li>
            </ul>
        </div>
    </div>

    {% block conteudo %}{% endblock %}

    <div class="footer">
        Simple MOOC - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>

simplemoc/core/templates/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

simplemoc/core/templates/contato.html
{% extends "base.html" %}


	{% block conteudo %}
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Contact Form #01</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-lg-10 col-md-12">
					<div class="wrapper">
						<div class="row no-gutters">
							<div class="col-md-7 d-flex align-items-stretch">
								<div class="contact-wrap w-100 p-md-5 p-4">
									<h3 class="mb-4">Get in touch</h3>
									<div id="form-message-warning" class="mb-4"></div>
				      		<div id="form-message-success" class="mb-4">
				            Your message was sent, thank you!
				      		</div>
									<form method="POST" id="contactForm" name="contactForm">
										<div class="row">
											<div class="col-md-6">
												<div class="form-group">
													<input type="text" class="form-control" name="name" id="name" placeholder="Name">
												</div>
											</div>
											<div class="col-md-6">
												<div class="form-group">
													<input type="email" class="form-control" name="email" id="email" placeholder="Email">
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<input type="text" class="form-control" name="subject" id="subject" placeholder="Subject">
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<textarea name="message" class="form-control" id="message" cols="30" rows="7" placeholder="Message"></textarea>
												</div>
											</div>
											<div class="col-md-12">
												<div class="form-group">
													<input type="submit" value="Send Message" class="btn btn-primary">
													<div class="submitting"></div>
												</div>
											</div>
										</div>
									</form>
								</div>
							</div>
							<div class="col-md-5 d-flex align-items-stretch">
								<div class="info-wrap bg-primary w-100 p-lg-5 p-4">
									<h3 class="mb-4 mt-md-4">Contact us</h3>
				        	<div class="dbox w-100 d-flex align-items-start">
				        		<div class="icon d-flex align-items-center justify-content-center">
				        			<span class="fa fa-map-marker"></span>
				        		</div>
				        		<div class="text pl-3">
					            <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
					          </div>
				          </div>
				        	<div class="dbox w-100 d-flex align-items-center">
				        		<div class="icon d-flex align-items-center justify-content-center">
				        			<span class="fa fa-phone"></span>
				        		</div>
				        		<div class="text pl-3">
					            <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
					          </div>
				          </div>
				        	<div class="dbox w-100 d-flex align-items-center">
				        		<div class="icon d-flex align-items-center justify-content-center">
				        			<span class="fa fa-paper-plane"></span>
				        		</div>
				        		<div class="text pl-3">
					            <p><span>Email:</span> <a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
					          </div>
				          </div>
				        	<div class="dbox w-100 d-flex align-items-center">
				        		<div class="icon d-flex align-items-center justify-content-center">
				        			<span class="fa fa-globe"></span>
				        		</div>
				        		<div class="text pl-3">
					            <p><span>Website</span> <a href="#">yoursite.com</a></p>
					          </div>
				          </div>
			          </div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>



	{% endblock %}

simplemoc/core/templates/home.html
{% extends "base.html" %}

{% block conteudo %}

    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        Uma Simples Plataforma de Ensino a Distância B
                    </h1>
                    <h2 class="splash-subhead">
                        O Simple MOOC visa simplificar o ensino a distância, provendo ferramentas objetivas e de fácil uso para cursos a distância.
                    </h2>
                    <p>
                        <a href="#" class="pure-button primary-button">Saiba mais</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
                    <h3>Publique suas aulas</h3>
                    <p>
                        O Simple MOOC tem um sistema simples e prático para que o professor disponibilize vídeo-aulas e materiais digitais como: pdf's, slides, imagens ...
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Vídeo aulas e materiais digitais.">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Fórum de Dúvidas">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Fórum de Dúvidas</h4>
                    <h3>Interaja com seus Alunos</h3>
                    <p>
                        No Simple MOOC você pode ter seu próprio sistema de fórum para que seus alunos possam interagir com você e com os outros alunos
                    </p>
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Exercícios</h4>
                    <h3>Crie exercícios para avaliar seus alunos</h3>
                    <p>
                        Você pode criar exercícios para que os alunos possam ser avaliados e todo o controle de notas e resolução dos exercícios é controlado pela plataforma, facilitando sua vida
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Exercícios">
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="http://placehold.it/400x250"
                         alt="Mural de Avisos">
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Mural de Avisos</h4>
                    <h3>Envie anúncios diretamente para os alunos</h3>
                    <p>
                        Organize os avisos do seu curso de forma fácil e simples.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        Simple MOOC - Uma simples plataforma de ensino a distância
    </div>
</div>
<script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
{% endblock %}
</html>

simplemoc/courses/templates/courses/details.html
{% extends "base.html" %}

{% block conteudo %}

{% load static %}
<div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        {{ course }}
                    </h1>
                    <h4 class="splash-subhead">
                        {{ course.descripton }}
                    </h4>
                    <p>
                        <a href="#" class="pure-button primary-button">Saiba mais</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Sobre o curso: </h4>
                    {{ course.about|linebreaks }}
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    {% if course.image %}
                    <img src="{{ course.image.url }}"  alt="">
                    {% else %}
                    <img src="{ static 'img/imagem.png}"  alt="">
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
     <div class="pure-g-r content-ribbon" id="contato">
        <div class="pure-u-1">
            <h3>Tire sua dúvida sobre o Curso</h3>
            {% if is_valid %}
            <p>Você enviou o formuláro com Sucesso</p>
            {% endif %}
            <form action="#contato" class="pure-form pure-form-aligned" method="post">
                {% csrf_token %}
                <fieldset>
                    {% for field in form %}
                    <div class="pure-control-group">
                        {{ field.label_tag }}
                        {{ field }}
                        {% if field.errors %}
                        <ul class="errorlist">
                            {% for error in field.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                    </div>
                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>

</div>

{% endblock %}

simplemoc/courses/templates/courses/index.html
{% extends "base.html" %}

{% block conteudo %}

{% load static %}


<div class="pure-g-r">

    <div class="content">
        {% for course in courses %}
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">
                    <a href="{{ course.get_absolute_url }}">
                        {{ course.name }}
                    </a></h4>
                    <h3>{{ course.name }}</h3>
                    <p>
                        {{ course.descripton | linebreaks }}
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <a href="{{ course.get_absolute_url }}">
                    {% if course.image %}
                    <img src="{{ course.image.url }}" alt="{{ course.name }}">
                    {% else %}
                    <img src="{% static 'img/Cursos-Online.png' %}" alt="">
                    {% endif %}
                    </a>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <p>
                        Nenhum curso está disponível na plataforma
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}